import { TrashIcon } from '@heroicons/react/24/outline';
import Head from 'next/head';
import React from 'react';
import Image from 'next/image';
import Header from '../components/Header';
import { useSelector } from 'react-redux';
import { selectItems, selectTotal } from '../slices/basketSlice';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';
import {
  ArrowSmallLeftIcon,
  ChevronRightIcon,
} from '@heroicons/react/24/solid';
import CartProduct from '../components/CartProduct';
import Link from 'next/link';

function CartPage() {
  const router = useRouter();
  // check sssion
  const { data: session } = useSession();

  // geet items & total from store
  const items = useSelector(selectItems);
  const total = useSelector(selectTotal);

  // create a checkout session
  const createCheckoutSession = () => {
    router.push('/shipping');
  };
  return (
    <div className="antialiased min-h-screen">
      <Head>
        <title>Checkout page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
        {/* cart content */}
        <div class="max-w-3xl p-4 space-y-10 mx-auto">
          {/* <!-- top --> */}
          <div class="flex-1 flex justify-between flex-row">
            <div>
              <ArrowSmallLeftIcon className="h-7 w-7 font-bold" />
            </div>

            <div>
              <h1 class="tracking-wider text-gray-900 text-lg font-medium">
                {items.length === 0 ? 'Cart is empty' : 'My Cart'}
              </h1>
            </div>

            <div>&nbsp;</div>
          </div>

          {/* <!-- items --> */}
          <div class="flex-1 flex border rounded-3xl py-6 px-6 w-full flex-col">
            {/* <div class="flex grid grid-cols-1 gap-6 block"> */}
            <div class="grid grid-cols-1 gap-6">
              {items.map((item, i) => (
                <CartProduct
                  key={i}
                  id={item.id}
                  title={item.title}
                  price={item.price}
                  description={item.description}
                  category={item.category}
                  image={item.image}
                />
              ))}
            </div>

            {items.length > 0 && (
              <div class="flex-1 flex justify-between flex-row mt-10">
                <div>
                  <p class="text-yellow-700 tracking-wider text-sm">
                    {items.length}
                  </p>
                </div>
                <div>
                  <p class="text-gray-900 tracking-wider font-medium">
                    {total}
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* <!-- cta --> */}
          <div class="flex-1 flex justify-center">
            <Link
              href={'/payment'}
              class="flex flex-row items-center justify-center space-x-4  w-full"
            >
              <span class="font-medium tracking-wider text-gray-900 ">
                Proceed to Checkout
              </span>

              <span class="p-1 bg-gray-200 rounded-lg">
                <ChevronRightIcon className="h-4 w-5 text-yellow-700 font-bold" />
              </span>
            </Link>
          </div>
        </div>
        {/* end cartcontent */}
      </main>
    </div>
  );
}

export default CartPage;
