import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Header from '../components/Header';

function checkout() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="lg:flex max-w-screen-2xl mx-auto">
        {/* left */}
        <div className="flex-grow m-5 shadow-sm">
          <Image
            src={'https://links.papareact.com/ikj'}
            alt={'alt'}
            width={1020}
            height={60}
          />
          <div className="flex flex-col p-5 space-y-10 bg-white">
            <h1 className='text-3xl border-b p-4'>Your Shopping basket </h1>
          </div>
        </div>
        {/* right */}
      </main>
    </div>
  );
}

export default checkout;
