import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import CheckoutWizard from '../components/CheckoutWizard';
import Header from '../components/Header';

function Payment() {
  const router = useRouter();
  const [selectedPaymentMethod, setSelectedPaymentMethod] = useState(null);

  const submitHandler = () => {};

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="lg:flex flex-col max-w-screen-sm py-5 mx-auto">
        <CheckoutWizard activeStep={2} />
        <form className="mx-auto max-w-screen-md">
          <h1>payment Method</h1>
          {['Paypal', 'CashOndelivery'].map((payment) => (
            <div key={payment} className="mb-4">
              <input
                className="p-2 outline-none focus:ring-0"
                id={payment}
                type="radio"
                checked={selectedPaymentMethod === payment}
                onChange={() => setSelectedPaymentMethod(payment)}
              />
            </div>
          ))}
          <div className="mb-4 flex justify-between">
            <button
              onClick={() => router.push('/shipping')}
              type="button"
              className="button"
            >
              Back
            </button>
            <button className="button">Next</button>
          </div>
        </form>
      </main>
    </div>
  );
}

export default Payment;
